/*
 * $FILE: hm.c
 *
 * health monitor management functions
 *
 * $VERSION$
 *
 * $AUTHOR$
 *
 * $LICENSE:
 * COPYRIGHT (c) Fent Innovative Software Solutions S.L.
 *     Read LICENSE.txt file for the license terms.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "common.h"
#include "xmc.h"

#define FILL_TAB(x) [x]=#x

char *hmLog[2]={
    FILL_TAB(XM_HM_LOG_DISABLED),
    FILL_TAB(XM_HM_LOG_ENABLED),
};

char *hmActions[XM_HM_MAX_ACTIONS]={
    FILL_TAB(XM_HM_AC_IGNORE),
    FILL_TAB(XM_HM_AC_SHUTDOWN),
    FILL_TAB(XM_HM_AC_PARTITION_COLD_RESET),
    FILL_TAB(XM_HM_AC_PARTITION_WARM_RESET),
    FILL_TAB(XM_HM_AC_HYPERVISOR_COLD_RESET),
    FILL_TAB(XM_HM_AC_HYPERVISOR_WARM_RESET),
    FILL_TAB(XM_HM_AC_SUSPEND),
    FILL_TAB(XM_HM_AC_PARTITION_HALT),
    FILL_TAB(XM_HM_AC_HYPERVISOR_HALT),
    FILL_TAB(XM_HM_AC_PROPAGATE),
    FILL_TAB(XM_HM_AC_SWITCH_TO_MAINTENANCE),
};

char *hmEvents[XM_HM_MAX_EVENTS]={
    FILL_TAB(XM_HM_EV_INTERNAL_ERROR),
    FILL_TAB(XM_HM_EV_SYSTEM_ERROR),
    FILL_TAB(XM_HM_EV_PARTITION_ERROR),
    FILL_TAB(XM_HM_EV_WATCHDOG_TIMER),
    FILL_TAB(XM_HM_EV_FP_ERROR),
    FILL_TAB(XM_HM_EV_MEM_PROTECTION),
    FILL_TAB(XM_HM_EV_UNEXPECTED_TRAP),
    
/*
    FILL_TAB(XM_HM_EV_INTERNAL_ERROR),
    FILL_TAB(XM_HM_EV_UNEXPECTED_TRAP),
    FILL_TAB(XM_HM_EV_PARTITION_UNRECOVERABLE),
    FILL_TAB(XM_HM_EV_PARTITION_ERROR),
    FILL_TAB(XM_HM_EV_PARTITION_INTEGRITY),
    FILL_TAB(XM_HM_EV_MEM_PROTECTION),
    FILL_TAB(XM_HM_EV_OVERRUN),
    FILL_TAB(XM_HM_EV_SCHED_ERROR),
    FILL_TAB(XM_HM_EV_WATCHDOG_TIMER),
    FILL_TAB(XM_HM_EV_INCOMPATIBLE_INTERFACE),
*/
#ifdef CONFIG_SPARCv8
    FILL_TAB(XM_HM_EV_SPARC_WRITE_ERROR),
    FILL_TAB(XM_HM_EV_SPARC_INSTR_ACCESS_MMU_MISS),
    FILL_TAB(XM_HM_EV_SPARC_INSTR_ACCESS_ERROR),
    FILL_TAB(XM_HM_EV_SPARC_REGISTER_HARDWARE_ERROR),
    FILL_TAB(XM_HM_EV_SPARC_INSTR_ACCESS_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARC_PRIVILEGED_INSTR),
    FILL_TAB(XM_HM_EV_SPARC_ILLEGAL_INSTR),
    FILL_TAB(XM_HM_EV_SPARC_FP_DISABLED),
    FILL_TAB(XM_HM_EV_SPARC_CP_DISABLED),
    FILL_TAB(XM_HM_EV_SPARC_UNIMPLEMENTED_FLUSH),
    FILL_TAB(XM_HM_EV_SPARC_WATCHPOINT_DETECTED),
    FILL_TAB(XM_HM_EV_SPARC_MEM_ADDR_NOT_ALIGNED),
    FILL_TAB(XM_HM_EV_SPARC_FP_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARC_CP_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARC_DATA_ACCESS_ERROR),
    FILL_TAB(XM_HM_EV_SPARC_DATA_ACCESS_MMU_MISS),
    FILL_TAB(XM_HM_EV_SPARC_DATA_ACCESS_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARC_TAG_OVERFLOW),
    FILL_TAB(XM_HM_EV_SPARC_DIVIDE_EXCEPTION),
#elif CONFIG_x86
    FILL_TAB(XM_HM_EV_X86_DIVIDE_ERROR),
    FILL_TAB(XM_HM_EV_X86_DEBUG),
    FILL_TAB(XM_HM_EV_X86_NMI_INTERRUPT),
    FILL_TAB(XM_HM_EV_X86_BREAKPOINT),
    FILL_TAB(XM_HM_EV_X86_OVERFLOW),
    FILL_TAB(XM_HM_EV_X86_BOUND_RANGE_EXCEEDED),
    FILL_TAB(XM_HM_EV_X86_INVALID_OPCODE),
    FILL_TAB(XM_HM_EV_X86_DEVICE_NOT_AVAILABLE),
    FILL_TAB(XM_HM_EV_X86_DOUBLE_FAULT),
    FILL_TAB(XM_HM_EV_X86_COPROCESSOR_SEGMENT_OVERRUN),
    FILL_TAB(XM_HM_EV_X86_INVALID_TSS),
    FILL_TAB(XM_HM_EV_X86_SEGMENT_NOT_PRESENT),
    FILL_TAB(XM_HM_EV_X86_STACK_FAULT),
    FILL_TAB(XM_HM_EV_X86_GENERAL_PROTECTION),
    FILL_TAB(XM_HM_EV_X86_PAGE_FAULT),
    FILL_TAB(XM_HM_EV_X86_X87_FPU_ERROR),
    FILL_TAB(XM_HM_EV_X86_ALIGNMENT_CHECK),
    FILL_TAB(XM_HM_EV_X86_MACHINE_CHECK),
    FILL_TAB(XM_HM_EV_X86_SIMD_FLOATING_POINT),
#endif
};

xm_u32_t ToHmAction(char *s, int line) {
    int e;
    for (e=0; e<XM_HM_MAX_ACTIONS; e++)
	if (hmActions[e]&&!strcmp(s, hmActions[e]))
	    return e;
    
    LineError(line, "Expected a valid Health Monitor action");
    return 0;
}

xm_u32_t ToHmEvent(char *s, int line) {
    int e;
    for (e=0; e<XM_HM_MAX_EVENTS; e++)
	if (hmEvents[e]&&!strcmp(s, hmEvents[e]))
	    return e;
   
    LineError(line, "Expected a valid Health Monitor event");
    return 0;
}

#define TOBIT(x) (1<<x)

static xm_u32_t hmPartEventsAndActions[XM_HM_MAX_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT), // CANNOT BE RAISED

    [XM_HM_EV_SYSTEM_ERROR]=TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_FP_ERROR]=TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

/*
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
*/
#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARC_WRITE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_INSTR_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_INSTR_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_INSTR_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_ILLEGAL_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_PRIVILEGED_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_FP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_CP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_UNIMPLEMENTED_FLUSH]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_WATCHPOINT_DETECTED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_REGISTER_HARDWARE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_MEM_ADDR_NOT_ALIGNED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_FP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_CP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_DATA_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_DATA_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARC_DATA_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_TAG_OVERFLOW]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARC_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
#elif CONFIG_x86
    [XM_HM_EV_X86_DIVIDE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_DEBUG]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_NMI_INTERRUPT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_BREAKPOINT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_OVERFLOW]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_BOUND_RANGE_EXCEEDED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_INVALID_OPCODE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_DEVICE_NOT_AVAILABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_DOUBLE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_COPROCESSOR_SEGMENT_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_INVALID_TSS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_SEGMENT_NOT_PRESENT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_STACK_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_GENERAL_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_PAGE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_X87_FPU_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_ALIGNMENT_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_MACHINE_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_X86_SIMD_FLOATING_POINT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_PARTITION_HALT)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
#endif
};

static xm_u32_t hmHpvEventsAndActions[XM_HM_MAX_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
   
    [XM_HM_EV_SYSTEM_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    [XM_HM_EV_FP_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
/*
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
*/
#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARC_WRITE_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_INSTR_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_INSTR_ACCESS_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_INSTR_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_ILLEGAL_INSTR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_PRIVILEGED_INSTR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_FP_DISABLED]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_CP_DISABLED]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_UNIMPLEMENTED_FLUSH]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_WATCHPOINT_DETECTED]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_REGISTER_HARDWARE_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_MEM_ADDR_NOT_ALIGNED]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_FP_EXCEPTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_CP_EXCEPTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_DATA_ACCESS_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_DATA_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),

    [XM_HM_EV_SPARC_DATA_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_TAG_OVERFLOW]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
    
    [XM_HM_EV_SPARC_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT),
#elif CONFIG_x86
    [XM_HM_EV_X86_DIVIDE_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_DEBUG]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_NMI_INTERRUPT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_BREAKPOINT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_OVERFLOW]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_BOUND_RANGE_EXCEEDED]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_INVALID_OPCODE]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_DEVICE_NOT_AVAILABLE]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_DOUBLE_FAULT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_COPROCESSOR_SEGMENT_OVERRUN]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_INVALID_TSS]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_SEGMENT_NOT_PRESENT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_STACK_FAULT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_GENERAL_PROTECTION]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_PAGE_FAULT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_X87_FPU_ERROR]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_ALIGNMENT_CHECK]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_MACHINE_CHECK]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_X86_SIMD_FLOATING_POINT]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_HALT)|TOBIT(XM_HM_AC_PROPAGATE),
#endif
};

static struct xmcHmSlot defaultPartHmTab[XM_HM_MAX_EVENTS]={
/* <track id="hm-part-default-conf"> */
    [XM_HM_EV_INTERNAL_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SYSTEM_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_FP_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },

    [XM_HM_EV_MEM_PROTECTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
/* </track id="hm-part-default-conf"> */
#ifdef CONFIG_SPARCv8
/* <track id="hm-part-default-conf-sparc"> */
    [XM_HM_EV_SPARC_WRITE_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_MMU_MISS]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_EXCEPTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_ILLEGAL_INSTR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_PRIVILEGED_INSTR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_FP_DISABLED]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_CP_DISABLED]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_UNIMPLEMENTED_FLUSH]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_WATCHPOINT_DETECTED]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_REGISTER_HARDWARE_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_MEM_ADDR_NOT_ALIGNED]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_FP_EXCEPTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_CP_EXCEPTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_MMU_MISS]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_EXCEPTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_TAG_OVERFLOW]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARC_DIVIDE_EXCEPTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
/* </track id="hm-part-default-conf-sparc"> */
#elif CONFIG_x86
/* <track id="hm-part-default-conf-x86"> */
    [XM_HM_EV_X86_DIVIDE_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_DEBUG]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_NMI_INTERRUPT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_BREAKPOINT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_OVERFLOW]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_BOUND_RANGE_EXCEEDED]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_INVALID_OPCODE]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_DEVICE_NOT_AVAILABLE]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_DOUBLE_FAULT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_COPROCESSOR_SEGMENT_OVERRUN]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_INVALID_TSS]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_SEGMENT_NOT_PRESENT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_STACK_FAULT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_GENERAL_PROTECTION]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_PAGE_FAULT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_X87_FPU_ERROR]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_ALIGNMENT_CHECK]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_MACHINE_CHECK]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_X86_SIMD_FLOATING_POINT]={.action=XM_HM_AC_PARTITION_HALT, .log=XM_HM_LOG_DISABLED, },
/* </track id="hm-part-default-conf-x86"> */
#endif
};

static struct xmcHmSlot defaultHpvHmTab[XM_HM_MAX_EVENTS]={
/* <track id="hm-xm-default-conf"> */
    [XM_HM_EV_INTERNAL_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SYSTEM_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_FP_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_MEM_PROTECTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
/* </track id="hm-xm-default-conf"> */
#ifdef CONFIG_SPARCv8
/* <track id="hm-xm-default-conf-sparc"> */
    [XM_HM_EV_SPARC_WRITE_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_MMU_MISS]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_INSTR_ACCESS_EXCEPTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_ILLEGAL_INSTR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_PRIVILEGED_INSTR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_FP_DISABLED]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_CP_DISABLED]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_UNIMPLEMENTED_FLUSH]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_WATCHPOINT_DETECTED]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_REGISTER_HARDWARE_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_MEM_ADDR_NOT_ALIGNED]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_FP_EXCEPTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_CP_EXCEPTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_MMU_MISS]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_DATA_ACCESS_EXCEPTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_TAG_OVERFLOW]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARC_DIVIDE_EXCEPTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
/* </track id="hm-xm-default-conf-sparc"> */
#elif CONFIG_x86
/* <track id="hm-xm-default-conf-x86"> */
    [XM_HM_EV_X86_DIVIDE_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_DEBUG]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_NMI_INTERRUPT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_BREAKPOINT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_OVERFLOW]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_BOUND_RANGE_EXCEEDED]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_INVALID_OPCODE]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_DEVICE_NOT_AVAILABLE]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_DOUBLE_FAULT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_COPROCESSOR_SEGMENT_OVERRUN]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_INVALID_TSS]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_SEGMENT_NOT_PRESENT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_STACK_FAULT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_GENERAL_PROTECTION]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_PAGE_FAULT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_X87_FPU_ERROR]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_ALIGNMENT_CHECK]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_MACHINE_CHECK]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_X86_SIMD_FLOATING_POINT]={.action=XM_HM_AC_HYPERVISOR_HALT, .log=XM_HM_LOG_ENABLED, },
/* </track id="hm-xm-default-conf-x86"> */
#endif
};

void SetupDefaultHpvHmActions(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultHpvHmTab, sizeof(struct xmcHmSlot)*XM_HM_MAX_EVENTS);
}

void SetupDefaultPartHmActions(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultPartHmTab, sizeof(struct xmcHmSlot)*XM_HM_MAX_EVENTS);
}


void HmHpvIsActionPermittedOnEvent(int event, int action, int line) {
    if (!(hmHpvEventsAndActions[event]&TOBIT(action)))
	LineError(line, "Action \"%s\" on event \"%s\" is not permitted", hmActions[action], hmEvents[event]);
}

void HmPartIsActionPermittedOnEvent(int event, int action, int line) {
    if (!(hmPartEventsAndActions[event]&TOBIT(action)))
	LineError(line, "Action \"%s\" on event \"%s\" is not permitted", hmActions[action], hmEvents[event]);
}

#ifdef CONFIG_CYCLIC_SCHED
void HmCheckExistMaintenancePlan(void) {
    int e, i, maintenance=0;
    // Are there any maintenance action?
    for (e=0;e<XM_HM_MAX_EVENTS; e++)
        if(xmc.hpv.hmTab[e].action==XM_HM_AC_SWITCH_TO_MAINTENANCE)
            maintenance=1;
    
    for (e=0; e<xmc.noPartitions; e++)
        for (i=0; i<XM_HM_MAX_EVENTS; i++)
            if (xmcPartitionTab[e].hmTab[i].action==XM_HM_AC_SWITCH_TO_MAINTENANCE)
                maintenance=1;       

    if (maintenance)
        // Is there a maintenance plan?
        for (e=0; e<xmc.hpv.noCpus; e++)
            if(xmc.hpv.cpuTab[e].noSchedCyclicPlans<2)
                LineError(xmcNoL.hpv.cpuTab[e].id, "Although required, a maintenance plan is not defined for CPU \"%d\"", xmc.hpv.cpuTab[e].id);
}
#endif
