#!/bin/bash
# Fent Innovative Software Solutions S.L.

dirname=$(dirname $0)
progname=$(basename $0)

function warn { echo -e $* 1>&2; }

if ! test -f $XTRATUM_PATH/xmconfig; then
    warn "\$XTRATUM_PATH variable undefined"
    exit 1;
fi

. $XTRATUM_PATH/xmconfig
. $XTRATUM_PATH/version

function changed { stat $1 | sed -n '$s|Change: ||p'; }
function digest {  sha1sum < $1 | sed 's|[ ]*-[ ]*||'; }
function usage { echo "usage: rswbuild <container> <output_file>"; }
function buildsummary {
    echo
    echo "Created by \"$USER\" on \"$HOSTNAME\" at \"`date`\""
    
    # check system integrity
    #xminstall -c -t $XTRATUM_PATH
    
    echo "XM path: \"$XTRATUM_PATH\""
    
    echo
    echo -e "XtratuM Core:"
    echo -e "   Version: \"$XTRATUMVERSION\""
    echo -e "   Arch:    \"$ARCH\""
    echo -e "   File:    \"$XTRATUM_PATH/core/xm_core.xef\""
    echo -e "   Sha1:    \"`digest $XTRATUM_PATH/core/xm_core.xef`\""
    echo -e "   Changed: \"`changed $XTRATUM_PATH/core/xm_core.xef`\""
    
    echo
    echo -e "XtratuM Library:"
    echo -e "   Version: \"$XM_VERSION.$XM_SUBVERSION.$XM_REVISION\""
    echo -e "   File:    \"$XTRATUM_PATH/user/libxm/libxm.a\""
    echo -e "   Sha1:    \"`digest $XTRATUM_PATH/user/libxm/libxm.a`\""
    echo -e "   Changed: \"`changed $XTRATUM_PATH/user/libxm/libxm.a`\""

    echo
    echo -e "XtratuM Tools:"
    echo -e "   File:    \"$XTRATUM_PATH/user/bin/xmcparser\""
    echo -e "   Sha1:    \"`digest $XTRATUM_PATH/user/bin/xmcparser`\""
#       echo -e "       xmlns:   \"`sed -n 's|[ ]*xmlns="\(.*\)"|\1|p' $XTRATUM_PATH/user/tools/xmcparser/xmc.xsd`\""
}

if test $# -ne 2; then
    warn `usage`
    exit 1;
fi

if ! test -e $1; then
    warn `usage`
    warn $progname: "error: file $CONTAINER not found"
    exit 1
fi

CONTAINER=$1
OFILE=$2

# report xtratum build summary
buildsummary

set -o errexit
echo | $TARGET_CC -x c $TARGET_CFLAGS_ARCH -c - -o tmp.o
$TARGET_OBJCOPY --add-section=.container=$CONTAINER --set-section-flags=.container=load,alloc tmp.o

RSW_PATH=$XTRATUM_PATH/user/bootloaders/rsw
LIBGCC=`$TARGET_CC -print-libgcc-file-name $TARGET_CFLAGS_ARCH `
TARGET_LDFLAGS="-T$RSW_PATH/$ARCH/rsw.lds $TARGET_LDFLAGS_ARCH $LIBGCC"
$TARGET_LD -n -S -o $OFILE $RSW_PATH/rsw_objs.o $TARGET_LDFLAGS tmp.o

chmod -x $OFILE
rm -f tmp.o
